# Generated by Django 4.2.2 on 2023-06-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_fullname', models.CharField(blank=True, max_length=60, null=True)),
                ('testimonial_position', models.CharField(blank=True, max_length=60, null=True)),
                ('testimonial_description', models.TextField(blank=True, max_length=500, null=True)),
                ('testimonial_review', models.TextField(blank=True, max_length=500, null=True)),
                ('testimonial_image', models.ImageField(upload_to='testimonial/')),
            ],
        ),
    ]
