# Generated by Django 4.2.2 on 2023-06-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureApp', '0003_color_material_product_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=60, null=True)),
                ('contact_surname', models.CharField(blank=True, max_length=60, null=True)),
                ('contact_description', models.TextField(blank=True, max_length=500, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
